services:
  moe-aggregate:
    image: moe-p:latest
    container_name: moe-aggregate
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    shm_size: "32gb"
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ..:/workspace
      - docker_hf-cache:/home/moe/.cache/huggingface
    environment:
      - HF_HOME=/home/moe/.cache/huggingface
      - HF_HUB_ENABLE_HF_TRANSFER=1
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN:-}
      - WANDB_API_KEY=${WANDB_API_KEY:-}
    working_dir: /workspace
    command: /bin/bash

volumes:
  docker_hf-cache:
    external: true

